version: '3.8'

services:
  # Service
  ox-test:
    image: open-xam-ox-test:latest
    environment:
      - DISPLAY=:99
    volumes:
      - ./e2e/artifacts/logs:/root/.open-xam-logs
      - ./e2e:/app/e2e
    command: >
      sh -c "
        rm -f $HOME/.open-xam/db/open-xam.db &&
        rm -f /tmp/.X99-lock &&
        Xvfb :99 -screen 0 1920x1080x24 -ac &
        XVFB_PID=$! &&
        cd /app/e2e &&
        npm test;
        kill $XVFB_PID
      "

volumes:
  ox-target: